### PR TITLE
Anubhav/Rito - now shutting down the cluster to prevent script waitin…

### PR DESCRIPTION
**Pull request by anubhavsri**
…g for all sessions to be closed before exit

### CODE REVIEW

**Comment by anubhavsri** [comment]
am not sure why build is getting hung. All tests are passing in my local.

**Comment by BryanSD** [comment]
👍 to the change, just need to figure out what's going on with the `flake8` tests before merging...

**Comment by anubhavsri** [comment]
right now flake8 is verifying all scripts including the libraries we are using. Is that mandatory?

**Comment by BryanSD** [comment]
Hmmm, only seems fair to validate this project and not any external dependencies (which may or may not validate with `flake8`). If what you're saying is true, I guess this behavior has been around for a while but never caused a problem until now. Feel free to open another PR to more narrowly focus `flake8`'s scope. After merging that, this PR should be good-to-go!

**Comment by anubhavsri** [comment]
done :) ignored the tox and eggs hidden directories to be scanned under flake8

**Comment by anubhavsri** [comment]
Hi Bryan,
Any updates on this merge?

**Comment by BryanSD** [comment]
Sorry @anubhavsri, just got busy with other things yesterday. Do you need a new release on PyPI as well?

**Comment by anubhavsri** [comment]
@BryanSD Thanks 👍 when can I start using this library with my changes? How frequent you release it to the PyPI?

**Comment by anubhavsri** [comment]
@BryanSD Any updates???

**Comment by BryanSD** [comment]
@anubhavsri: Hoping to have time to push this out today

**Comment by BryanSD** [comment]
@anubhavsri: Happy Friday! https://pypi.python.org/pypi/cdeploy/1.7

**Comment by anubhavsri** [comment]
thanks a lot :)

**Pull request merged**
