### PR TITLE
Make cassandra session timeout configurable.

### PR DESCRIPTION
**Pull request by andrew-vant**
Every so often I have a need for this and not having it bugs me. I tried to write it in a way that would make it easy to add additional session options later if needed.

I ran tox against it; one test consistently failed, but as it was failing on the connect() call complaining about not being able to connect, I assume it's not because of this code. I just don't have a local cassandra running. I can't vouch for this being correct beyond that.

### CODE REVIEW

**Comment by BryanSD** [comment]
:+1: 

I'd like to get one review from another Engineering member for usage and another from a developer, please: @powellchristoph @Kuwagata @isaacm @yuemin-li

**Comment by yuemin-li** [comment]
👍

**Comment by andrew-vant** [comment]
@powellchristoph: See above. @BryanSD wanted your opinion on this, I think because you use cdeploy as well.

**Comment by powellchristoph** [comment]
:+1:

**Pull request merged**
